SIM                 = icarus
TOPLEVEL_LANG       = verilog
VERILOG_SOURCES     = $(shell pwd)/alu.v
TOPLEVEL            = alu
COCOTB_TEST_MODULES = test_alu
COCOTB_RESULTS_FILE = results_alu.xml
SIM_BUILD           = sim_build_alu

include $(shell cocotb-config --makefiles)/Makefile.sim
